
version: "3"
services:

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: bkool_db
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: myadmin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  bkool-pruebatecnica:
    image: bkool-pruebatecnica:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

volumes:
  postgres_data:
