spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/bkool_db"
#    url: "jdbc:postgresql://db:5432/bkool_db"
    username: myadmin
    password: myadmin