spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/bkool_db"
#    url: "jdbc:postgresql://db:5432/bkool_db"
    username: myadmin
    password: myadmin
  cache:
    type: redis
  redis:
    host: localhost
#    host: redis
    port: 6379
cache:
  config:
    entryTtl: 60
    bike:
      entrtyTtl: 30